---
kind: pipeline
name: default
when:
  ref:
    include:
      - refs/tags/**

steps:
- name: Create voltagex/fedora-mingw64-qemu image  
  image: plugins/docker
# Only rebuild the Fedora/MinGW container when we tag container specifically
# e.g. git tag container-0.2 && git push origin --tags
  when:
    ref:
      include: 
        - refs/tags/container-*
  settings:
    username: voltagex
    password:
      from_secret: docker_auth
    repo: voltagex/fedora-mingw64-qemu
    dockerfile: Dockerfile.fedora-builder

- name: Get QEMU sources
  image: docker:git
  when:
# Only build and release qemu when we tag a release
# e.g. git tag release-0.2 && git push origin --tags
    ref:
      - refs/tags/release-*
  commands:
  - git clone https://github.com/qemu/qemu --recursive

- name: Build QEMU via mingw64 via Docker
  image: voltagex/fedora-mingw64-qemu
  when:
    ref:
      - refs/tags/release-*
  environment:
    UPLOAD_AUTH:
      from_secret: upload_auth
  commands:
  - mv drone-helper.sh qemu/ && cd qemu && ./drone-helper.sh
  
- name: publish  
  image: plugins/github-release
  when:
    ref:
      include: 
        - refs/tags/release-*
  settings:
    api_key:
      from_secret: github_token
    files: /qemu.tar.gz
    
