---
kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
#  Only rebuild the Fedora/MinGW container when we tag container specifically
  trigger:
    ref:
      include: refs/tags/container-*
  settings:
    username: voltagex
    password:
      from_secret: docker_auth
    repo: voltagex/fedora-mingw64-qemu
    dockerfile: Dockerfile.fedora-builder

- name: Get QEMU sources
  image: docker:git
  commands:
  - git clone https://github.com/qemu/qemu --recursive

- name: Build QEMU via mingw64 via Docker
  image: voltagex/fedora-mingw64-qemu
  environment:
    UPLOAD_AUTH:
      from_secret: upload_auth
  commands:
  - mv drone-helper.sh qemu/ && cd qemu && ./drone-helper.sh
  
- name: publish  
  image: plugins/github-release
  trigger:
    ref:
      include: refs/tags/release-*
  settings:
    api_key:
      from_secret: github_token
    files: /qemu.tar.gz
    
